apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-backend-service
  labels:
    app: python-backend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-backend-service
  template:
    metadata:
      labels:
        app: python-backend-service
    spec:
      containers:
      - name: python-backend-service
        image: asrafbd/python-backend:v1
        imagePullPolicy: Always
      #imagePullSecrets:
      #- name: dockerhub



---

apiVersion: v1
kind: Service
metadata:
  name: python-backend-service
  labels:
    run: python-backend-service
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    nodePort: 30007
  selector:
    app: python-backend-service
