apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: frontend-deployment
  template:
    metadata:
      labels:
        component: frontend-deployment
    spec:
      containers:
      - name: frontend
        #image: asrafbd/react-frontend:v1
        image: amdadulbari/optmizers:frontendv3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: amdadul-reg-cred



---

apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport-service
spec:
  type: NodePort
  selector:
    component: frontend-deployment
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30006
